spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce-micro
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
  application:
    name: inventory-service