app:
  name: tempo
  container:
    image:
      name: grafana/tempo
      version: 2.7.2
    targetPort:
      http: 3200
      grpc: 4317
    limits:
      cpu: 300m
      memory: 512Mi

service:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 3200
      targetPort: 3200