spring:
  config:
    import: configserver:http://config-service:8888
  kafka:
    bootstrap-servers: kafka-1:9090, kafka-2:9090, kafka-3:9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8070/eureka/
