spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventories/**
      default-filters:
        - TokenRelay=
        - name: RateLimiter
          args:
            fallbackUri: /fallback/rateLimit
        - name: CircuitBreaker
          args:
            fallbackUri: forward:/fallback/circuitBreaker
resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5


eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true

