spring:
application:
  name: product-service
security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:8080/realms/ecommerce-microservices/protocol/openid-connect/certs
datasource:
  url: jdbc:postgresql://localhost:5432/ecommerce-micro
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: postgres
liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.yaml
jpa:
  show-sql: true
kafka:
  bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true