spring:
  datasource:
    url: jdbc:postgresql://inventory-postgres:5432/ecommerce-micro-inventory
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
  application:
    name: inventory-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecommerce-microservices/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8070/eureka/