apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentelemetry-agent-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
  volumeName: opentelemetry-agent-pv