apiVersion: v1
kind: PersistentVolume
metadata:
  name: opentelemetry-agent-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/otel-agent
    type: DirectoryOrCreate