spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecommerce-microservices/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ecommerce-microservices

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

server:
  port: 1000