spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
  application:
    name: product-service
  config:
    import: configserver:http://config-service:8888
