spring:
  config:
    import: configserver:http://config-service:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8070/eureka/

microservices:
  api:
    inventory: http://inventory-service:8080/api/inventories
