spring:
  application:
    name: product-service

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true

microservices:
  api:
    inventory: http://inventory-service