spring:
  config:
    import: configserver:http://localhost:8888
server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

microservices:
  api:
    inventory: http://localhost:9004/api/inventories
