spring:
  config:
    import: configserver:http://config-service:8888

microservices:
  api:
    product:
      findByIds: http://product-service:8082/api/products/batch
    inventory:
      checkForStock: http://inventory-service:8084/api/inventory/check

