spring:
  application:
    name: inventory-service

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true

microservices:
  api:
    product: http://product-service