spring:
  config:
    import: configserver:http://localhost:8888
server:
  port: 9004


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

microservices:
  api:
    product: http://localhost:9002/api/products
