app:
  name: order-service
  initContainer:
    name: wait-for-config-service
    image:
      name: curlimages/curl
      version: 8.4.0
  container:
    image:
      name: andreiyankavets/order-service
      version: latest
    port: 8083
    targetPort: 8080
    limits:
      cpu: 400m
      memory: 512Mi
