apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.container.image.name }}:{{ .Values.app.container.image.version }}"
          imagePullPolicy: IfNotPresent
          args: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: {{ .Values.app.container.targetPort }}
          resources:
            limits:
              cpu: {{ .Values.app.container.limits.cpu }}
              memory: {{ .Values.app.container.limits.memory }}
