apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.container.image.name }}:{{ .Values.app.container.image.version }}"
          imagePullPolicy: IfNotPresent
          args: ["-config.file=/etc/loki/loki-config.yaml"]
          volumeMounts:
            - name: {{ .Values.app.name }}-storage
              mountPath: /loki/tsdb
              subPath: tsdb
            - name: {{ .Values.app.name }}-storage
              mountPath: /loki/wal
              subPath: wal
            - name: {{ .Values.app.name }}-storage
              mountPath: /loki/cache
              subPath: cache
            - name: {{ .Values.app.name }}-storage
              mountPath: /loki/index
              subPath: index
            - name: {{ .Values.app.name }}-storage
              mountPath: /loki/delete-requests
              subPath: delete-requests
            - name: {{ .Values.app.name }}-storage
              mountPath: /data/retention
              subPath: retention
            - name: config
              mountPath: /etc/loki/
          ports:
            - containerPort: {{ .Values.app.container.targetPort }}
          resources:
            limits:
              cpu: {{ .Values.app.container.limits.cpu }}
              memory: {{ .Values.app.container.limits.memory }}

      volumes:
        - name: {{ .Values.app.name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc
        - name: config
          configMap:
            name: {{ .Values.app.name }}-config