apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-pv
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.49.100
    path: /k8s/{{ .Values.app.name }}