spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ecommerce-microservices/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ecommerce-microservices

server:
  port: 1001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

